#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "joplin"
name = "Joplin"
description.en = "Note taking and to-do application with synchronisation capabilities"
description.fr = "Application de prise de notes et de tâches avec capacités de synchronisation"

version = "3.2.12~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://joplinapp.org/"
admindoc = "https://joplinapp.org/help/"
code = "https://github.com/laurent22/joplin/"

[integration]
yunohost = ">= 12.0.8"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "5G"
ram.build = "4G"
ram.runtime = "280M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/laurent22/joplin/archive/refs/tags/v3.2.12.tar.gz"
        sha256 = "4b292df1b1e5042f671c58ccb3241296064c8e96a1c32d647bc38f7c54311904"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 22300

    [resources.data_dir]

    [resources.apt]
    packages = "postgresql, postgresql-client, python3-bcrypt, rsync"

    [resources.database]
    type = "postgresql"
